# -*- coding: utf-8 -*-
"""base code_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5xUWQqr-I7saOCyoLvsDrIAMDrg0RjZ
"""

# ======================
# 0. Kaggle API로 데이터 자동 다운로드 (Drive X)
# ======================

import os
from pathlib import Path

# Colab에 kaggle.json 업로드해야 함
# ⚠️ 아래 셀 실행하면 파일 업로드 창 뜸
from google.colab import files
files.upload()  # kaggle.json 업로드하세요

# kaggle.json 세팅
os.makedirs('/root/.kaggle', exist_ok=True)
os.system('mv kaggle.json /root/.kaggle/')
os.system('chmod 600 /root/.kaggle/kaggle.json')

# Kaggle에서 데이터 다운로드
!kaggle competitions download -c state-farm-distracted-driver-detection -p ./dataset
!unzip -qq ./dataset/state-farm-distracted-driver-detection.zip -d ./dataset

base_dir = Path("./dataset/state-farm-distracted-driver-detection")

print("✅ 데이터 다운로드 완료:", base_dir.exists())

!pip install kaggle
from google.colab import files
files.upload()

ls -1ha kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

# Permission Warning 방지
!chmod 600 ~/.kaggle/kaggle.json

!kaggle competitions download -c state-farm-distracted-driver-detection

!unzip state-farm-distracted-driver-detection

# ======================
# 1. 기본 설정
# ======================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from tqdm.notebook import tqdm
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from sklearn.model_selection import KFold
import os

# GPU 자동 선택
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'사용 디바이스: {device}')


# ======================
# 2. 경로 설정
# ======================

from pathlib import Path
import os

base_dir = Path("/content")

driver_csv_path = base_dir / "driver_imgs_list.csv"
train_dir = base_dir / "imgs" / "train"
test_dir = base_dir / "imgs" / "test"

print("✅ CSV 경로:", driver_csv_path)
print("✅ Train 경로:", train_dir)
print("✅ Test 경로:", test_dir)

print("CSV 존재 여부:", driver_csv_path.exists())
print("Train 폴더 존재 여부:", train_dir.exists())
print("Test 폴더 존재 여부:", test_dir.exists())


# ======================
# 3. 하이퍼파라미터
# ======================
img_size = 224
batch_size = 32 if device.type == 'cuda' else 8
num_classes = 10
num_epochs = 10
learning_rate = 1e-4
num_workers = 2 if device.type == 'cuda' else 0


# ======================
# 4. 데이터 로딩
# ======================
driver_df = pd.read_csv(driver_csv_path)
all_drivers = sorted(driver_df['subject'].unique())

n_folds = 5
kfold = KFold(n_splits=n_folds, shuffle=True, random_state=42)

fold_splits = []
for fold_idx, (train_indices, val_indices) in enumerate(kfold.split(all_drivers)):
    train_drivers = [all_drivers[i] for i in train_indices]
    val_drivers = [all_drivers[i] for i in val_indices]
    fold_splits.append({
        'fold': fold_idx + 1,
        'train_drivers': train_drivers,
        'val_drivers': val_drivers
    })

print(f"총 {n_folds}개 fold 중 1개만 학습 예정.")


# ======================
# 5. Dataset 정의
# ======================
class DriverDataset(Dataset):
    def __init__(self, data_dir, driver_df, driver_list, transform=None, is_test=False):
        self.data_dir = data_dir
        self.transform = transform
        self.is_test = is_test
        self.images, self.labels = [], []

        if is_test:
            for img_name in os.listdir(data_dir):
                self.images.append(os.path.join(data_dir, img_name))
        else:
            subset = driver_df[driver_df['subject'].isin(driver_list)]
            for _, row in subset.iterrows():
                class_name = row['classname']
                img_name = row['img']
                img_path = os.path.join(data_dir, class_name, img_name)
                self.images.append(img_path)
                self.labels.append(int(class_name[1:]))
        print(f"{'테스트셋' if is_test else f'운전자 {len(driver_list)}명'}, 이미지 {len(self.images)}개")

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = self.images[idx]
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        if self.is_test:
            return image, os.path.basename(img_path)
        else:
            label = self.labels[idx]
            return image, label


# ======================
# 6. Transform 설정
# ======================
transform_train = transforms.Compose([
    transforms.RandomResizedCrop(img_size, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.RandomGrayscale(p=0.1),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

transform_eval = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.CenterCrop(img_size),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])



# ======================
# 7. 학습 / 검증 함수
# ======================
def train_epoch(model, loader, criterion, optimizer):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for inputs, labels in tqdm(loader, desc="Training"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        _, preds = torch.max(outputs, 1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    return running_loss / total, 100 * correct / total


def validate(model, loader, criterion):
    model.eval()
    running_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in tqdm(loader, desc="Validating"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            running_loss += loss.item() * inputs.size(0)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    return running_loss / total, 100 * correct / total


# ======================
# 8. Fold 1개만 학습
# ======================
fold_info = fold_splits[0]
fold_idx = fold_info['fold']
train_drivers = fold_info['train_drivers']
val_drivers = fold_info['val_drivers']

print(f"\n========== Fold {fold_idx} 시작 ==========")

train_dataset = DriverDataset(train_dir, driver_df, train_drivers, transform_train)
val_dataset = DriverDataset(train_dir, driver_df, val_drivers, transform_eval)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

# ✅ VGG16 모델 (weights 버전 호환)
model = models.vgg16(weights='IMAGENET1K_V1')
model.classifier[6] = nn.Linear(4096, num_classes)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

best_val_loss = float('inf')
best_model_path = f'best_vgg16_fold{fold_idx}.pth'
history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

for epoch in range(num_epochs):
    print(f"\nEpoch [{epoch+1}/{num_epochs}]")
    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer)
    val_loss, val_acc = validate(model, val_loader, criterion)
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)

    print(f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.2f}% | Val Loss: {val_loss:.4f}, Acc: {val_acc:.2f}%")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save({'model_state_dict': model.state_dict()}, best_model_path)
        print(f"✅ Best model saved at {best_model_path}")

print(f"\nFold {fold_idx} 완료! Best Val Loss: {best_val_loss:.4f}")


# ======================
# 9. 테스트셋 예측 (Kaggle 제출용)
# ======================
print("\n📦 테스트 데이터 예측 중...")

test_dataset = DriverDataset(test_dir, driver_df, [], transform_eval, is_test=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

checkpoint = torch.load(best_model_path, map_location=device)
model.load_state_dict(checkpoint['model_state_dict'])
model.eval()

all_preds = []
img_names = []

with torch.no_grad():
    for imgs, filenames in tqdm(test_loader, desc="Predicting"):
        imgs = imgs.to(device)
        outputs = model(imgs)
        probs = torch.softmax(outputs, dim=1)
        all_preds.append(probs.cpu().numpy())
        img_names.extend(filenames)

all_preds = np.vstack(all_preds)
print("✅ 예측 완료!")

submission = pd.DataFrame({
    'img': img_names,
    **{f'c{i}': all_preds[:, i] for i in range(10)}
})

submission_file = 'vgg16_fold1_submission.csv'
submission.to_csv(submission_file, index=False)
print(f"\n✅ Submission 파일 생성 완료: {submission_file}")
print(submission.head())

# ======================
# 1. 기본 설정
# ======================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from tqdm.notebook import tqdm
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from sklearn.model_selection import KFold
import os

# GPU 자동 선택
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'사용 디바이스: {device}')


# ======================
# 2. 경로 설정
# ======================

from pathlib import Path
import os

base_dir = Path("/content")

driver_csv_path = base_dir / "driver_imgs_list.csv"
train_dir = base_dir / "imgs" / "train"
test_dir = base_dir / "imgs" / "test"

print("✅ CSV 경로:", driver_csv_path)
print("✅ Train 경로:", train_dir)
print("✅ Test 경로:", test_dir)

print("CSV 존재 여부:", driver_csv_path.exists())
print("Train 폴더 존재 여부:", train_dir.exists())
print("Test 폴더 존재 여부:", test_dir.exists())


# ======================
# 3. 하이퍼파라미터
# ======================
img_size = 224
batch_size = 32 if device.type == 'cuda' else 8
num_classes = 10
num_epochs = 10
learning_rate = 1e-4
num_workers = 2 if device.type == 'cuda' else 0


# ======================
# 4. 데이터 로딩
# ======================
driver_df = pd.read_csv(driver_csv_path)
all_drivers = sorted(driver_df['subject'].unique())

n_folds = 5
kfold = KFold(n_splits=n_folds, shuffle=True, random_state=42)

fold_splits = []
for fold_idx, (train_indices, val_indices) in enumerate(kfold.split(all_drivers)):
    train_drivers = [all_drivers[i] for i in train_indices]
    val_drivers = [all_drivers[i] for i in val_indices]
    fold_splits.append({
        'fold': fold_idx + 1,
        'train_drivers': train_drivers,
        'val_drivers': val_drivers
    })

print(f"총 {n_folds}개 fold 중 1개만 학습 예정.")


# ======================
# 5. Dataset 정의
# ======================
class DriverDataset(Dataset):
    def __init__(self, data_dir, driver_df, driver_list, transform=None, is_test=False):
        self.data_dir = data_dir
        self.transform = transform
        self.is_test = is_test
        self.images, self.labels = [], []

        if is_test:
            for img_name in os.listdir(data_dir):
                self.images.append(os.path.join(data_dir, img_name))
        else:
            subset = driver_df[driver_df['subject'].isin(driver_list)]
            for _, row in subset.iterrows():
                class_name = row['classname']
                img_name = row['img']
                img_path = os.path.join(data_dir, class_name, img_name)
                self.images.append(img_path)
                self.labels.append(int(class_name[1:]))
        print(f"{'테스트셋' if is_test else f'운전자 {len(driver_list)}명'}, 이미지 {len(self.images)}개")

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = self.images[idx]
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        if self.is_test:
            return image, os.path.basename(img_path)
        else:
            label = self.labels[idx]
            return image, label


# ======================
# 6. Transform 설정
# ======================
from torchvision import transforms

transform_train = transforms.Compose([
    transforms.Resize((256, 256)),  # 기본 리사이즈
    transforms.ToTensor(),          # PIL Image를 Tensor로 변환
    transforms.RandomApply([        # 랜덤하게 Sharpen 적용
        transforms.GaussianBlur(kernel_size=(3, 3), sigma=(0.1, 1.5))
    ], p=0.3),
    transforms.RandomAffine(degrees=10, translate=(0.05, 0.05)),  # 약간의 이동/회전
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.25, contrast=0.3, saturation=0.2, hue=0.02),
    transforms.RandomErasing(p=0.2, scale=(0.02, 0.15), ratio=(0.3, 3.3), value='random'),
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

transform_eval = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])



# ======================
# 7. 학습 / 검증 함수
# ======================
def train_epoch(model, loader, criterion, optimizer):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for inputs, labels in tqdm(loader, desc="Training"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        _, preds = torch.max(outputs, 1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    return running_loss / total, 100 * correct / total


def validate(model, loader, criterion):
    model.eval()
    running_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in tqdm(loader, desc="Validating"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            running_loss += loss.item() * inputs.size(0)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    return running_loss / total, 100 * correct / total


# ======================
# 8. Fold 1개만 학습
# ======================
fold_info = fold_splits[0]
fold_idx = fold_info['fold']
train_drivers = fold_info['train_drivers']
val_drivers = fold_info['val_drivers']

print(f"\n========== Fold {fold_idx} 시작 ==========")

train_dataset = DriverDataset(train_dir, driver_df, train_drivers, transform_train)
val_dataset = DriverDataset(train_dir, driver_df, val_drivers, transform_eval)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

# ✅ VGG16 모델 (weights 버전 호환)
model = models.vgg16(weights='IMAGENET1K_V1')
model.classifier[6] = nn.Linear(4096, num_classes)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

best_val_loss = float('inf')
best_model_path = f'best_vgg16_fold{fold_idx}.pth'
history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

for epoch in range(num_epochs):
    print(f"\nEpoch [{epoch+1}/{num_epochs}]")
    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer)
    val_loss, val_acc = validate(model, val_loader, criterion)
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)

    print(f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.2f}% | Val Loss: {val_loss:.4f}, Acc: {val_acc:.2f}%")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save({'model_state_dict': model.state_dict()}, best_model_path)
        print(f"✅ Best model saved at {best_model_path}")

print(f"\nFold {fold_idx} 완료! Best Val Loss: {best_val_loss:.4f}")


# ======================
# 9. 테스트셋 예측 (Kaggle 제출용)
# ======================
print("\n📦 테스트 데이터 예측 중...")

test_dataset = DriverDataset(test_dir, driver_df, [], transform_eval, is_test=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

checkpoint = torch.load(best_model_path, map_location=device)
model.load_state_dict(checkpoint['model_state_dict'])
model.eval()

all_preds = []
img_names = []

with torch.no_grad():
    for imgs, filenames in tqdm(test_loader, desc="Predicting"):
        imgs = imgs.to(device)
        outputs = model(imgs)
        probs = torch.softmax(outputs, dim=1)
        all_preds.append(probs.cpu().numpy())
        img_names.extend(filenames)

all_preds = np.vstack(all_preds)
print("✅ 예측 완료!")

submission = pd.DataFrame({
    'img': img_names,
    **{f'c{i}': all_preds[:, i] for i in range(10)}
})

submission_file = 'vgg16_submission_v2.csv'
submission.to_csv(submission_file, index=False)
print(f"\n✅ Submission 파일 생성 완료: {submission_file}")
print(submission.head())